- charts/dp-config-aks/Chart.yaml
- charts/dp-config-aks/templates/certificate-production.yaml
- charts/dp-config-aks/templates/certificate-staging.yaml
- charts/dp-config-aks/values.yaml
- dev/lint-chart-locally.sh
- docs/dp-cluster-workshop/aks/README.md
- docs/dp-cluster-workshop/aks/aks-cluster-create.sh
- docs/dp-cluster-workshop/aks/clean-up.sh
- docs/dp-cluster-workshop/aks/post-aks-cluster-script.sh
- docs/dp-cluster-workshop/aks/pre-aks-cluster-script.sh
Update workshop doc for aks and eks on behalf of @nashtapu-tibco
> Update workshop doc

- charts/dp-core-infrastructure/Chart.yaml
- charts/dp-core-infrastructure/charts/haproxy-ingress/templates/controller-hpa.yaml
- charts/dp-core-infrastructure/charts/haproxy-ingress/values.yaml
- charts/dp-core-infrastructure/values.yaml
- Update parent dp-core-infra helm chart
> PDP-1848: Promote infra helm charts to public github repo

- charts/tibco-developer-hub/Chart.yaml
- charts/tibco-developer-hub/charts/common/README.md
- charts/tibco-developer-hub/charts/postgresql/README.md
- charts/tibco-developer-hub/templates/_generated.tpl
- charts/tibco-developer-hub/templates/_helpers.tpl
- charts/tibco-developer-hub/templates/backstage-deployment.yaml
- charts/tibco-developer-hub/values.yaml
Updated public repo for tibco-developer-hub 1.1.0.
> Updated public repo for tibco-developer-hub 1.1.0.

- charts/tp-cp-hawk/.helmignore
- charts/tp-cp-hawk/Chart.yaml
- charts/tp-cp-hawk/LICENCE
- charts/tp-cp-hawk/charts/tp-cp-hawk-infra-prometheus/Chart.yaml
- charts/tp-cp-hawk/charts/tp-cp-hawk-infra-prometheus/LICENSE
- charts/tp-cp-hawk/charts/tp-cp-hawk-infra-prometheus/templates/_consts.tpl
- charts/tp-cp-hawk/charts/tp-cp-hawk-infra-prometheus/templates/_helpers.tpl
- charts/tp-cp-hawk/charts/tp-cp-hawk-infra-prometheus/templates/_shared.tpl
- charts/tp-cp-hawk/charts/tp-cp-hawk-infra-prometheus/templates/fluentbit-configmap.yaml
- charts/tp-cp-hawk/charts/tp-cp-hawk-infra-prometheus/templates/prometheus-config.yaml
- charts/tp-cp-hawk/charts/tp-cp-hawk-infra-prometheus/templates/prometheus-service.yaml
- charts/tp-cp-hawk/charts/tp-cp-hawk-infra-prometheus/templates/prometheus-statefuleset.yaml
- charts/tp-cp-hawk/charts/tp-cp-hawk-infra-prometheus/templates/prometheus-tibco-route.yaml
- charts/tp-cp-hawk/charts/tp-cp-hawk-infra-prometheus/values.yaml
- charts/tp-cp-hawk/charts/tp-cp-hawk-infra-querynode/Chart.yaml
- charts/tp-cp-hawk/charts/tp-cp-hawk-infra-querynode/LICENSE
- charts/tp-cp-hawk/charts/tp-cp-hawk-infra-querynode/templates/_consts.tpl
- charts/tp-cp-hawk/charts/tp-cp-hawk-infra-querynode/templates/_helpers.tpl
- charts/tp-cp-hawk/charts/tp-cp-hawk-infra-querynode/templates/_shared.tpl
- charts/tp-cp-hawk/charts/tp-cp-hawk-infra-querynode/templates/querynode-deployment.yaml
- charts/tp-cp-hawk/charts/tp-cp-hawk-infra-querynode/templates/querynode-service.yaml
- charts/tp-cp-hawk/charts/tp-cp-hawk-infra-querynode/values.yaml
- charts/tp-cp-hawk/templates/_consts.tpl
- charts/tp-cp-hawk/templates/_helpers.tpl
- charts/tp-cp-hawk/templates/_shared.tpl
- charts/tp-cp-hawk/templates/tphawkinfra-jobs.yaml
- charts/tp-cp-hawk/templates/tphawkinfra-secret.yaml
- charts/tp-cp-hawk/values.yaml
> sync tp-cp-hawk chart to public tp-helm-charts

- charts/oauth2-proxy-manifests/Chart.yaml
- charts/oauth2-proxy-manifests/templates/_tibco.tpl
- charts/oauth2-proxy-manifests/templates/deployment.yaml
- charts/oauth2-proxy-manifests/templates/fluentbit-configmap.yaml
- charts/oauth2-proxy-manifests/templates/pre-delete-job.yaml
- charts/oauth2-proxy-manifests/templates/shell-script-cm.yaml
- charts/oauth2-proxy-manifests/values.yaml
PCP-5792 sync with dev chart oauth2proxy
> PCP-5792 sync with dev chart oauth2proxy

- charts/tibco-developer-hub/Chart.yaml
- charts/tibco-developer-hub/charts/common/README.md
- charts/tibco-developer-hub/charts/postgresql/README.md
- charts/tibco-developer-hub/templates/app-config-configmap.yaml
- charts/tibco-developer-hub/templates/backstage-deployment.yaml
- charts/tibco-developer-hub/templates/fluentbit-configmap.yaml
- charts/tibco-developer-hub/templates/well-known-configuration-ingress.yaml
- charts/tibco-developer-hub/values.yaml
- charts/tp-cp-tibcohub-contrib/.helmignore
- charts/tp-cp-tibcohub-contrib/Chart.yaml
- charts/tp-cp-tibcohub-contrib/templates/_functions.tpl
- charts/tp-cp-tibcohub-contrib/templates/_helpers.tpl
- charts/tp-cp-tibcohub-contrib/templates/job.yaml
- charts/tp-cp-tibcohub-contrib/values.yaml
- charts/tp-cp-tibcohub-recipes/.helmignore
- charts/tp-cp-tibcohub-recipes/Chart.yaml
- charts/tp-cp-tibcohub-recipes/templates/_consts.tpl
- charts/tp-cp-tibcohub-recipes/templates/_functions.tpl
- charts/tp-cp-tibcohub-recipes/templates/_helpers.tpl
- charts/tp-cp-tibcohub-recipes/templates/_shared.tpl
- charts/tp-cp-tibcohub-recipes/templates/recipe-script.yaml
- charts/tp-cp-tibcohub-recipes/templates/tibcohub.yaml
- charts/tp-cp-tibcohub-recipes/values.yaml
Pushed 1.2.0 tibco hub related charts to public repo.
#PLTDX-1126
> Pushed 1.2.0 tibco hub related charts to public repo.

- docs/workshop/cp-cluster/eks/README.md
- docs/workshop/scripts/eks/create-efs.sh
- docs/workshop/scripts/eks/create-rds.sh
Addressed issues:
1. https://github.com/TIBCOSoftware/tp-helm-charts/issues/51
2. https://github.com/TIBCOSoftware/tp-helm-charts/issues/54
3. https://github.com/TIBCOSoftware/tp-helm-charts/issues/55
> workshop-fixes: address issues related to postgres version and create tags

- docs/workshop/dp-cluster/aks/README.md
Updated the workshop AKS data plane cluster creation to fix https://jira.tibco.com/browse/PLTDX-1153
#PLTDX-1153
> PLTDX-1153

- charts/oauth2-proxy-manifests/Chart.yaml
- charts/oauth2-proxy-manifests/templates/deployment.yaml
- charts/oauth2-proxy-manifests/templates/ingress.yaml
- charts/oauth2-proxy-manifests/templates/pre-delete-job.yaml
- charts/oauth2-proxy-manifests/templates/shell-script-cm.yaml
- charts/oauth2-proxy-manifests/values.yaml
- charts/oauth2-proxy-recipes/Chart.yaml
- charts/oauth2-proxy-recipes/templates/_helpers.tpl
- charts/oauth2-proxy-recipes/templates/oauth2proxy.yaml
- charts/oauth2-proxy-recipes/values.yaml
> [PCP-6874] Promote Oauth2Proxy helm charts to public github repo 

- docs/workshop/microk8s/bare-metal-data-plane/README.md
fix typo in file link of jaeger span rollover index json
> Update BMDP workshop README.md

- .github/workflows/release-chart.yaml
Also upgrade action helm version
> [PDP-3335] Add release branch github action

- charts/tibco-developer-hub/Chart.yaml
- charts/tibco-developer-hub/templates/_helpers.tpl
- charts/tibco-developer-hub/templates/backstage-deployment.yaml
- charts/tibco-developer-hub/values.yaml
- charts/tp-cp-tibcohub-recipes/Chart.yaml
- charts/tp-cp-tibcohub-recipes/templates/tibcohub.yaml
Pushed 1.3.0-HF1 Tibco Hub related charts to public repo.
> Pushed 1.3.0-HF1 Tibco Hub related charts to public repo.

- charts/tp-cp-recipes/Chart.yaml
Bumped tp-cp-recipes helm chart to 1.3.171.
> Bumped tp-cp-recipes helm chart to 1.3.171.

- charts/platform-base/Chart.yaml
Bumped platform-base helm chart to 1.3.344.
> Bumped platform-base helm chart to 1.3.344.

- charts/tp-cp-core-finops/Chart.yaml
- charts/tp-cp-core-finops/charts/finops-service/Chart.yaml
- charts/tp-cp-core-finops/charts/finops-service/templates/_consts.tpl
- charts/tp-cp-core-finops/charts/finops-service/templates/_generated.tpl
- charts/tp-cp-core-finops/charts/finops-service/templates/finops-service.yaml
- charts/tp-cp-core-finops/charts/finops-service/values.yaml
- charts/tp-cp-core-finops/charts/monitoring-service/Chart.yaml
- charts/tp-cp-core-finops/charts/monitoring-service/templates/_consts.tpl
- charts/tp-cp-core-finops/charts/monitoring-service/templates/_generated.tpl
- charts/tp-cp-core-finops/charts/monitoring-service/templates/monitoring-service.yaml
- charts/tp-cp-core-finops/charts/monitoring-service/values.yaml
- charts/tp-cp-core-finops/templates/_consts.tpl
- charts/tp-cp-core-finops/templates/_generated.tpl
- charts/tp-cp-core-finops/templates/jobs.yaml
- charts/tp-cp-core-finops/values.yaml
This is just pulled over directly from the private repo.
> Monitoring and finops charts for 1.3.0-HF3.

- charts/tp-cp-infra-recipes/Chart.yaml
- charts/tp-cp-infra-recipes/templates/_helpers.tpl
- charts/tp-cp-servicemesh-recipes/Chart.yaml
- charts/tp-cp-servicemesh-recipes/templates/_helpers.tpl
> Merging the remaining tp-cp-infra-recipe and tp-cp-servicemesh-recipe

- charts/tp-cp-recipes/Chart.yaml
Pushed tp-cp-recipes chart to open source repo.
> Pushed tp-cp-recipes chart to open source repo.

- charts/platform-base/Chart.yaml
- charts/platform-base/values.yaml
Bumping up the Platform base build 1.3.437.
> Bumping up the Platform base build 1.3.437.

- charts/platform-bootstrap/Chart.yaml
> Bumping missing bootstrap chart

- docs/workshop/aks/control-plane/README.md
* add the CP on Azure doc on behalf of Prateek
> [PCP-8936] add CP on Azure workshop

- charts/oauth2-proxy-manifests/Chart.yaml
- charts/oauth2-proxy-manifests/templates/deployment.yaml
- charts/oauth2-proxy-manifests/templates/fluentbit-configmap.yaml
- charts/oauth2-proxy-manifests/templates/pre-delete-job.yaml
- charts/oauth2-proxy-manifests/values.yaml
- charts/oauth2-proxy-recipes/Chart.yaml
- charts/oauth2-proxy-recipes/README.md
- charts/oauth2-proxy-recipes/templates/oauth2proxy.yaml
- charts/oauth2-proxy-recipes/values.yaml
Publishing OAuth2 proxy 1.4.0 Charts.
> Publishing OAuth2 proxy 1.4.0 Charts.

- charts/tibco-developer-hub/Chart.yaml
- charts/tibco-developer-hub/charts/postgresql/Chart.lock
- charts/tibco-developer-hub/charts/postgresql/templates/primary/statefulset.yaml
- charts/tibco-developer-hub/templates/_helpers.tpl
- charts/tibco-developer-hub/templates/backstage-deployment.yaml
- charts/tibco-developer-hub/templates/fluentbit-configmap.yaml
- charts/tibco-developer-hub/templates/ingress_public_traefik.yaml
- charts/tibco-developer-hub/templates/well-known-configuration-ingress-nginx.yaml
- charts/tibco-developer-hub/values.yaml
- charts/tp-cp-tibcohub-contrib/Chart.yaml
- charts/tp-cp-tibcohub-contrib/templates/_helpers.tpl
- charts/tp-cp-tibcohub-contrib/templates/job.yaml
- charts/tp-cp-tibcohub-contrib/values.yaml
- charts/tp-cp-tibcohub-recipes/Chart.yaml
- charts/tp-cp-tibcohub-recipes/templates/_helpers.tpl
- charts/tp-cp-tibcohub-recipes/templates/tibcohub.yaml
- charts/tp-cp-tibcohub-recipes/values.yaml
Publishing Tibco developer hub 1.4.0 Charts.
> Publishing Tibco developer hub 1.4.0 Charts.

- charts/tibco-developer-hub/Chart.yaml
- charts/tibco-developer-hub/templates/backstage-deployment.yaml
- charts/tp-cp-tibcohub-recipes/Chart.yaml
- charts/tp-cp-tibcohub-recipes/templates/tibcohub.yaml
Fixed PLTDX-1467: Developer hub provisioning issue when there is a star in no_proxy value
> Fixed PLTDX-1467: Developer hub provisioning issue when there is a star in no_proxy value

- charts/tp-cp-recipes/Chart.yaml
Pushing tp-cp-recipes chart version 1.4.152 which has the fix for PLTDX-1467
> Pushing tp-cp-recipes chart version 1.4.152 which has the fix for PLTDX-1467

- charts/tibco-developer-hub/Chart.yaml
- charts/tibco-developer-hub/templates/backstage-deployment.yaml
- charts/tibco-developer-hub/values.yaml
- charts/tp-cp-tibcohub-recipes/Chart.yaml
- charts/tp-cp-tibcohub-recipes/templates/tibcohub.yaml
Pushing PLTDX-1469 related changes to public repo for developer hub.
> Pushing PLTDX-1469 related changes to public repo for developer hub.

- charts/tp-cp-recipes/Chart.yaml
Bumped tp-cp-recipes chart to 1.4.153 for the fix PLTDX-1469
> Bumped tp-cp-recipes chart to 1.4.153 for the fix PLTDX-1469

- charts/tibco-developer-hub/Chart.yaml
- charts/tibco-developer-hub/templates/backstage-deployment.yaml
- charts/tibco-developer-hub/values.yaml
- charts/tp-cp-tibcohub-contrib/Chart.yaml
- charts/tp-cp-tibcohub-contrib/values.yaml
- charts/tp-cp-tibcohub-recipes/Chart.yaml
- charts/tp-cp-tibcohub-recipes/templates/tibcohub.yaml
- charts/tp-cp-tibcohub-recipes/values.yaml
Copied dev hub related helm charts to public repo.
> Copied dev hub related helm charts to public repo.

- charts/oauth2-proxy-manifests/Chart.yaml
- charts/oauth2-proxy-manifests/values.yaml
- charts/oauth2-proxy-recipes/Chart.yaml
- charts/oauth2-proxy-recipes/README.md
- charts/oauth2-proxy-recipes/templates/oauth2proxy.yaml
- charts/oauth2-proxy-recipes/values.yaml
Publishing OAuth2 proxy 1.5.0 Charts.
> Publishing OAuth2 proxy 1.5.0 Charts.

- charts/platform-base/Chart.yaml
- charts/tp-cp-core-ops/Chart.yaml
- charts/tp-cp-core/Chart.yaml
- charts/tp-cp-core/charts/identity-management/Chart.yaml
- charts/tp-cp-core/charts/identity-management/templates/_consts.tpl
- charts/tp-cp-core/charts/identity-management/templates/idm.yaml
Upgrading platform base to 1.5.155.
Upgrading tp-cp-core and tp-cp-core-ops build to 1.5.8686.
> Upgrading platform base to 1.5.155.

- charts/oauth2-proxy-manifests/Chart.yaml
- charts/oauth2-proxy-manifests/values.yaml
- charts/oauth2-proxy-recipes/Chart.yaml
- charts/oauth2-proxy-recipes/templates/oauth2proxy.yaml
- charts/oauth2-proxy-recipes/values.yaml
Publishing OAuth2 proxy 1.5.1 Charts.
> Publishing OAuth2 proxy 1.5.1 Charts.

- charts/tibco-developer-hub/Chart.yaml
- charts/tibco-developer-hub/values.yaml
- charts/tp-cp-tibcohub-recipes/Chart.yaml
- charts/tp-cp-tibcohub-recipes/templates/tibcohub.yaml
- charts/tp-cp-tibcohub-recipes/values.yaml
Publishing Tibco Developer Hub 1.5.1 Charts to public repo.
> Publishing Tibco Developer Hub 1.5.1 Charts to public repo.

- charts/tp-cp-core-ops/Chart.yaml
- charts/tp-cp-core-ops/templates/_generated.tpl
- charts/tp-cp-core-ops/templates/create_admin_user.yaml
- charts/tp-cp-core/Chart.yaml
- charts/tp-cp-core/charts/admin-webserver/Chart.yaml
- charts/tp-cp-core/charts/admin-webserver/templates/_generated.tpl
- charts/tp-cp-core/charts/admin-webserver/templates/admin-webserver.yaml
- charts/tp-cp-core/charts/cronjobs/Chart.yaml
- charts/tp-cp-core/charts/cronjobs/templates/_generated.tpl
- charts/tp-cp-core/charts/email-service/Chart.yaml
- charts/tp-cp-core/charts/email-service/templates/_generated.tpl
- charts/tp-cp-core/charts/identity-management/Chart.yaml
- charts/tp-cp-core/charts/identity-management/templates/_generated.tpl
- charts/tp-cp-core/charts/identity-management/templates/idm.yaml
- charts/tp-cp-core/charts/identity-provider/Chart.yaml
- charts/tp-cp-core/charts/identity-provider/templates/_generated.tpl
- charts/tp-cp-core/charts/orchestrator/Chart.yaml
- charts/tp-cp-core/charts/orchestrator/templates/_generated.tpl
- charts/tp-cp-core/charts/pengine/Chart.yaml
- charts/tp-cp-core/charts/pengine/templates/_generated.tpl
- charts/tp-cp-core/charts/user-subscriptions/Chart.yaml
- charts/tp-cp-core/charts/user-subscriptions/templates/_generated.tpl
- charts/tp-cp-core/charts/web-server/Chart.yaml
- charts/tp-cp-core/charts/web-server/templates/_generated.tpl
- charts/tp-cp-core/charts/web-server/templates/cp-webserver.yaml
- charts/tp-cp-core/templates/_generated.tpl
**Description**
Publishing the RC1 for tp-cp-core and tp-cp-core-ops 151 release.
> Publishing the RC1 for tp-cp-core and tp-cp-core-ops 151 release.

- charts/platform-base/Chart.yaml
Updated Chart dependencies:
```
- name: tp-cp-recipes
version: "1.5.1018"
repository: alias:tibco-platform
- name: tp-cp-o11y
version: "1.5.1000"
repository: alias:tibco-platform
- name: tp-cp-core
version: "1.5.10017"
repository: alias:tibco-platform
- name: tp-cp-core-ops
version:  "1.5.10017"
repository: alias:tibco-platform
- name: tp-cp-core-finops
version: "1.5.549"
repository: alias:tibco-platform
- name: tp-cp-integration
version: : "1.5.39"
```
> platform-base: 1.5.1048

- docs/workshop/aks/cluster-setup/README.md
- docs/workshop/aks/control-plane/README.md
Fixed
Issue 1 - Command in Enable Preview Features corrected
Issue 2 - Public Docs Link corrected
Issue 3 - Certificate for Control Plane
> PCP-10910: Fix AKS READMEs certificate and semantic issues

- charts/oauth2-proxy-manifests/Chart.yaml
- charts/oauth2-proxy-manifests/values.yaml
- charts/oauth2-proxy-recipes/Chart.yaml
- charts/oauth2-proxy-recipes/templates/oauth2proxy.yaml
- charts/oauth2-proxy-recipes/values.yaml
Publishing OAuth2 proxy 1.6.0 Charts.
> Publishing OAuth2 proxy 1.6.0 Charts.

- charts/tp-cp-core-ops/Chart.yaml
- charts/tp-cp-core/Chart.yaml
- charts/tp-cp-core/charts/identity-management/Chart.yaml
- charts/tp-cp-core/charts/identity-management/templates/_generated.tpl
- charts/tp-cp-core/charts/identity-management/templates/idm.yaml
Publishing the CP Core 160 RC2
> Publishing the CP Core 160 RC2

- charts/oauth2-proxy-manifests/Chart.yaml
- charts/oauth2-proxy-manifests/templates/ingress.yaml
- charts/oauth2-proxy-manifests/values.yaml
- charts/oauth2-proxy-recipes/Chart.yaml
- charts/oauth2-proxy-recipes/templates/_helpers.tpl
- charts/oauth2-proxy-recipes/templates/oauth2proxy.yaml
- charts/oauth2-proxy-recipes/values.yaml
Publishing oauth2-proxy charts for 1.7.0.
> Publishing oauth2-proxy charts for 1.7.0.

- .github/workflows/lint-test.yaml
- .github/workflows/release-chart-label.yaml
- .github/workflows/release-chart.yaml
changes: 
* upgrade tools version
* add helm dependency build
> [PCP-12542] update chart build action

- index.yaml
I have removed the tags and releases already. Using this PR, I am cleaning up the index.yaml.
> PCP-13114: Cleanup 1.2.0 and pre-1.2.0 charts from public repo

- charts/dp-configure-namespace/Chart.yaml
- charts/dp-configure-namespace/charts/config/Chart.yaml
- charts/dp-configure-namespace/charts/haproxy/Chart.yaml
- charts/dp-core-infrastructure/Chart.yaml
- charts/dp-core-infrastructure/charts/tp-provisioner-agent/Chart.yaml
- charts/dp-core-infrastructure/charts/tp-provisioner-agent/values.yaml
- charts/dp-core-infrastructure/charts/tp-tibtunnel/Chart.yaml
- charts/dp-core-infrastructure/charts/tp-tibtunnel/values.yaml
- charts/o11y-service/Chart.yaml
- charts/o11y-service/templates/configmap.yaml
- charts/o11y-service/values.yaml
- charts/tp-cp-proxy/Chart.yaml
- charts/tp-cp-proxy/values.yaml
- docs/workshop/Dockerfile
- docs/workshop/aks/cluster-setup/README.md
- docs/workshop/aks/control-plane/README.md
- docs/workshop/aro (Azure Red Hat OpenShift)/cluster-setup/README.md
- docs/workshop/aro (Azure Red Hat OpenShift)/control-plane/README.md
- docs/workshop/aro (Azure Red Hat OpenShift)/data-plane/README.md
- docs/workshop/eks/cluster-setup/README.md
- docs/workshop/eks/cluster-setup/eksctl-recipe.yaml
- docs/workshop/eks/control-plane/README.md
- docs/workshop/eks/scripts/create-rds.sh
- docs/workshop/vCluster/README.md
dp-configure-namespace,  dp-core-infrastructure, tp-provisioner-agent, o11y-service, tp-cp-proxy
> promoting infra/o11y charts

- charts/platform-addon-eventprocessing/Chart.yaml
- charts/tp-cp-eventprocessing-be/Chart.yaml
- charts/tp-cp-eventprocessing-be/charts/be-webserver/Chart.yaml
- charts/tp-cp-eventprocessing-be/charts/be-webserver/values.yaml
> Promote plarform addon eventprocessing basechart for 1.11.0. [DONT MERGE]
